import { expect, type Locator, type Page } from '@playwright/test';

// TYING THE MESSAGE TO THE FIELD (issues #12 and #37).
//
// Checking that an error text is "visible somewhere" says nothing about what
// was missing: the LINK between the faulty field and its message. These
// assertions hold the link itself — the field is marked invalid, and the
// message that DESCRIBES it (`aria-describedby`) is indeed that one.

export async function expectFieldError(
  page: Page,
  field: Locator,
  message: string | RegExp,
): Promise<void> {
  await expect(field).toHaveAttribute('aria-invalid', 'true');
  const describedBy = (await field.getAttribute('aria-describedby')) ?? '';
  const ids = describedBy.split(/\s+/).filter(Boolean);
  expect(ids.length, 'le champ ne décrit aucun message').toBeGreaterThan(0);

  // A field may be described by its hint AND its error: we search among
  // both. Attribute selector rather than `#id` — the IDs generated by
  // React contain ":", which is not a valid CSS selector.
  const described = page.locator(ids.map((id) => `[id="${id}"]`).join(', '));
  await expect(described.filter({ hasText: message })).toHaveCount(1);
}

export async function expectNoFieldError(field: Locator): Promise<void> {
  await expect(field).not.toHaveAttribute('aria-invalid', 'true');
}

// CHOOSING IN A SHADCN LIST.
//
// The site's selects are no longer native: a button with the `combobox`
// role opens a list of `option`s — Radix Select, or the searchable cmdk list
// for the long ones. `selectOption` has nothing to act on; a person clicks the
// field, then the line they want, by its visible label. The list is portalled
// to the end of the page: the option is looked up on the page, not inside the
// locator that holds the field.
export async function chooseOption(
  field: Locator,
  option: string | RegExp,
): Promise<void> {
  await field.click();
  await field
    .page()
    .getByRole('option', { name: option, exact: typeof option === 'string' })
    .click();
  await expect(field).toHaveAttribute('aria-expanded', 'false');
}
