// Public routes that respond 200 in both languages without Convex.
// The five Convex-backed pages (bibliotheque, experts, le-reseau,
// thematiques, tribune) are excluded: they respond 500 here — that is a
// separate finding (F-02), not a reason to skew the SEO/a11y measurements.
export const PUBLIQUES = [
  '',
  '/a-propos',
  '/accessibilite',
  '/actualites',
  '/adhesion',
  '/appels-a-projets',
  '/barometre',
  '/confidentialite',
  '/connexion',
  '/connexion-otp',
  '/contact',
  '/don',
  '/evenements',
  '/evenements/calendrier',
  '/jeunes',
  '/mentions-legales',
  '/mot-de-passe-oublie',
  '/newsletter',
  '/newsletter/desinscription',
  '/partenaires',
  '/presse',
  '/rapports',
  '/recherche',
  '/replays',
] as const;
